# -*- coding: utf-8 -*-
"""steamgames.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VneIjVrgb7IYzKOM4TEeDLp4DSbQJ4Ll
"""

import pandas as pd
import duckdb

# Cargar el dataset desde la URL
dataframe = pd.read_csv('https://raw.githubusercontent.com/velocirenaptor/steam_project/refs/heads/main/steam_games.csv')

# Consulta SQL corregida
consulta = """
SELECT name, COUNT(*) AS rating_count
FROM dataframe
GROUP BY name
ORDER BY rating_count DESC
"""

# Ejecutar con DuckDB y obtener el DataFrame resultante
df = duckdb.sql(consulta).df()
df

import pandas as pd
import duckdb

dataframe = pd.read_csv('https://raw.githubusercontent.com/velocirenaptor/steam_project/refs/heads/main/steam_games.csv')

consulta_metacritic = """
SELECT name, metacritic, developers, "price_initial (USD)"
FROM dataframe
WHERE metacritic IS NOT NULL
ORDER BY metacritic DESC
LIMIT 10;
"""
df = duckdb.sql(consulta_metacritic).df()
df

import pandas as pd
import duckdb

dataframe = pd.read_csv('https://raw.githubusercontent.com/velocirenaptor/steam_project/refs/heads/main/steam_games.csv')

consulta_devs = """
SELECT developers, COUNT(*) AS total_juegos
FROM dataframe
WHERE developers IS NOT NULL AND developers != ''
GROUP BY developers
ORDER BY total_juegos DESC
LIMIT 10;
"""
df = duckdb.sql(consulta_devs).df()
df

import pandas as pd
import duckdb

dataframe = pd.read_csv('https://raw.githubusercontent.com/velocirenaptor/steam_project/refs/heads/main/steam_games.csv')

consulta_reviews = """
SELECT name, total_reviews, total_positive, positive_percentual
FROM dataframe
ORDER BY total_reviews DESC
LIMIT 10;
"""
df = duckdb.sql(consulta_reviews).df()
df

import pandas as pd
import duckdb

dataframe = pd.read_csv('https://raw.githubusercontent.com/velocirenaptor/steam_project/refs/heads/main/steam_games.csv')

consulta_f2p = """
SELECT name, positive_percentual, total_reviews, genres
FROM dataframe
WHERE is_free = TRUE AND total_reviews > 1000
ORDER BY positive_percentual DESC
LIMIT 10;
"""
df = duckdb.sql(consulta_f2p).df()
df

import pandas as pd
import duckdb

dataframe = pd.read_csv('https://raw.githubusercontent.com/velocirenaptor/steam_project/refs/heads/main/steam_games.csv')

consulta_precios = """
SELECT name, "price_initial (USD)", developers, genres
FROM dataframe
WHERE "price_initial (USD)" IS NOT NULL
ORDER BY "price_initial (USD)" DESC
LIMIT 10;
"""

df = duckdb.sql(consulta_precios).df()
df
df

# Markdown cell: ### 1.1. Proporción de edad requerida y su distribucion
consulta_distribucion = """
SELECT required_age, COUNT(*) AS cantidad
FROM dataframe
GROUP BY required_age
ORDER BY cantidad DESC;
"""

df_distribucion = duckdb.sql(consulta_distribucion).df()
df_distribucion

# Markdown cell: ### 1.2.juegos free to play vs de paga
consulta = """
SELECT is_free, COUNT(*) AS cantidad
FROM dataframe
GROUP BY is_free;
"""
df = duckdb.sql(consulta).df()
df

# Markdown cell: ### 1.3. Top por genero
consulta_top_por_genero = """
WITH juegos_ordenados AS (
    SELECT
        genres,
        name,
        total_reviews,
        ROW_NUMBER() OVER (PARTITION BY genres ORDER BY total_reviews DESC) AS ranking
    FROM dataframe
    WHERE genres IS NOT NULL AND total_reviews > 0
)
SELECT genres, name, total_reviews
FROM juegos_ordenados
WHERE ranking <= 3
ORDER BY genres, ranking;
"""

df = duckdb.sql(consulta_top_por_genero).df()
df

# Markdown cell: ### 1.4. Combinaciones Frecuentes entre Sombrero y Esporada
consulta_detalle_anio = """
SELECT
    SUBSTR(release_date, 1, 4) AS anio_lanzamiento,
    name,
    total_positive,
    total_negative
FROM dataframe
WHERE release_date IS NOT NULL AND LENGTH(release_date) >= 4
ORDER BY anio_lanzamiento DESC, total_positive DESC;
"""

df = duckdb.sql(consulta_detalle_anio).df()
df

import pandas as pd
import matplotlib.pyplot as plt

# 1. Crear tabla cruzada entre la calificación de reseña y si es gratis
crosstab_steam = pd.crosstab(dataframe['review_score_desc'], dataframe['is_free'])

# 2. Generar el gráfico de barras apiladas
plt.figure(figsize=(10, 6))
crosstab_steam.plot(kind='bar', stacked=True, figsize=(10, 6), colormap='Set2')

plt.title("Distribución del Tipo de Reseña según si el Juego es Gratis o de Pago", fontsize=12)
plt.xlabel("Descripción de la Reseña")
plt.ylabel("Cantidad de Juegos")
plt.xticks(rotation=45, ha='right') # Rota las etiquetas para que no se encimen
plt.grid(axis='y', linestyle='--', alpha=0.5)

# Personalizar leyenda (False = De pago, True = Gratis)
plt.legend(["De Pago (False)", "Gratuito (True)"], title="¿Es Gratis?")

plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
# Usamos review_score_desc en el eje X e is_free para diferenciar el color (hue)
sns.countplot(data=dataframe, x='review_score_desc', hue='is_free', palette=['#1f77b4', '#ff7f0e'])

plt.title("Frecuencia de Juegos por Tipo de Reseña y si son Gratuitos", fontsize=12)
plt.xlabel("Descripción de la Reseña")
plt.ylabel("Cantidad de Juegos")
plt.legend(title="¿Es Gratis?")
plt.xticks(rotation=45, ha='right') # Rota las etiquetas si son largas
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

crosstab_matriz = pd.crosstab(dataframe['review_score_desc'], dataframe['is_free'])

plt.figure(figsize=(9, 6))
sns.heatmap(crosstab_matriz, annot=True, fmt="d", cmap="YlGnBu")
plt.title("Frecuencia de Juegos: Tipo de Reseña vs. Si es Gratuito")
plt.xlabel("¿Es Gratuito? (is_free)")
plt.ylabel("Descripción de la Reseña")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx

G = nx.Graph()

# Agrupar datos por la descripción de la reseña y el género
relaciones = (
    dataframe.groupby(['review_score_desc', 'genres'])
    .size()
    .reset_index(name='peso')
)

# Filtramos solo las 20 relaciones con más peso para que el grafo sea legible
relaciones = relaciones.nlargest(20, 'peso')

for _, row in relaciones.iterrows():
    node_review = f"Review: {row['review_score_desc']}"
    node_genre = f"Género: {row['genres']}"

    G.add_node(node_review, type='review')
    G.add_node(node_genre, type='genre')
    # Guardamos el atributo explícitamente como 'peso'
    G.add_edge(node_review, node_genre, peso=row['peso'])

# Definir colores para diferenciar nodos
color_map = []
for node in G.nodes():
    if 'Género:' in node:
        color_map.append('#FF6F61')  # Color para el género
    else:
        color_map.append('#6BAED6')  # Color para la reseña

plt.figure(figsize=(12, 8))
pos = nx.spring_layout(G, k=0.8, seed=42)

# Normalizar grosores de líneas leyendo el atributo 'peso'
max_p = (
    max([d['peso'] for u, v, d in G.edges(data=True)])
    if len(G.edges()) > 0
    else 1
)
weights = [(d['peso'] / max_p) * 6 + 1 for u, v, d in G.edges(data=True)]

# Dibujar nodos y conexiones
nx.draw_networkx_nodes(
    G, pos, node_color=color_map, node_size=1500, alpha=0.9
)
nx.draw_networkx_edges(G, pos, width=weights, alpha=0.6, edge_color='gray')
nx.draw_networkx_labels(G, pos, font_size=8, font_weight='bold')

plt.title(
    'Grafo de Red: Relación entre Tipo de Reseña y Género del Juego',
    fontsize=12,
)
plt.axis('off')
plt.tight_layout()
plt.show()